## Preprocessing

In [41]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.tail()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [42]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME', Status, and special consideration
application_df= application_df.drop(columns= ["EIN", "NAME", "STATUS", "SPECIAL_CONSIDERATIONS"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1

In [43]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [44]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [45]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff_value=1065
application_types_to_replace = app_type_counts[app_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Look at CLASSIFICATION value counts for binning
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_types_updated= classification_types.loc[classification_types > 1]
classification_types_updated

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [46]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value_classification = 1883
classifications_to_replace = classification_types [classification_types < cutoff_value_classification].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [47]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded= pd.get_dummies(application_df)
application_df_encoded.tail(20)

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
34279,11442,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
34280,401661,0,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
34281,56261,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
34282,5000,0,0,0,0,0,0,1,1,0,...,1,1,0,0,0,0,0,0,0,0
34283,5000,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
34284,3384856,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
34285,5000,1,0,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
34286,5000,0,0,0,1,0,0,0,1,0,...,1,1,0,0,0,0,0,0,0,0
34287,6713,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
34288,5000,0,0,0,1,0,0,0,1,0,...,1,1,0,0,0,0,0,0,0,0
34289,20197,1,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
34290,5000,0,0,0,0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
34291,5000,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34292,5000,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34293,5000,1,0,0,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34294,5000,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
34295,5000,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34296,5000,0,0,0,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34297,5000,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
34298,36500179,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [48]:
# Split our preprocessed data into our features and target arrays
y = application_df_encoded['IS_SUCCESSFUL'].values
X =application_df_encoded.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [49]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [54]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=128, activation="relu", input_dim=37))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=128, activation="tanh"))

#THIRD hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 128)               4864

 dense_25 (Dense)            (None, 128)               16512

 dense_26 (Dense)            (None, 100)               12900

 dense_27 (Dense)            (None, 1)                 101

=================================================================
Total params: 34377 (134.29 KB)
Trainable params: 34377 (134.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [55]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [57]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7396
Epoch 2/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5371 - accuracy: 0.7406
Epoch 3/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7405
Epoch 4/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7393
Epoch 5/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7387
Epoch 6/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7378
Epoch 7/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7385
Epoch 8/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7397
Epoch 9/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7396
Epoch 10/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7404
Epoch 11/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7392
Epoch 12/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7398
Epoch 13/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7402
Epoch 14/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7407
Epoch 15/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7391
Epoch 16/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7406
Epoch 17/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7400
Epoch 18/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7402
Epoch 19/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7401
Epoch 20/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7389
Epoch 21/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5373 - accuracy: 0.7399
Epoch 22/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7402
Epoch 23/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7404
Epoch 24/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7394
Epoch 25/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7408
Epoch 26/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7411
Epoch 27/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7413
Epoch 28/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7399
Epoch 29/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7423
Epoch 30/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7395
Epoch 31/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7388
Epoch 32/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7413
Epoch 33/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7409
Epoch 34/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5373 - accuracy: 0.7409
Epoch 35/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7410
Epoch 36/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7395
Epoch 37/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7402
Epoch 38/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7406
Epoch 39/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7395
Epoch 40/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7404
Epoch 41/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5368 - accuracy: 0.7414
Epoch 42/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7396
Epoch 43/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7403
Epoch 44/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7392
Epoch 45/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7411
Epoch 46/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7407
Epoch 47/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7405
Epoch 48/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5375 - accuracy: 0.7408
Epoch 49/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7416
Epoch 50/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7395
Epoch 51/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7403
Epoch 52/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7398
Epoch 53/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7405
Epoch 54/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7409
Epoch 55/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5376 - accuracy: 0.7409
Epoch 56/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7404
Epoch 57/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7393
Epoch 58/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7401
Epoch 59/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7393
Epoch 60/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7401
Epoch 61/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7396
Epoch 62/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7407
Epoch 63/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7404
Epoch 64/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7389
Epoch 65/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7395
Epoch 66/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7405
Epoch 67/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7406
Epoch 68/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5374 - accuracy: 0.7395
Epoch 69/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7406
Epoch 70/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7402
Epoch 71/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7401
Epoch 72/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7399
Epoch 73/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7393
Epoch 74/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7390
Epoch 75/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5372 - accuracy: 0.7406
Epoch 76/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7400
Epoch 77/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7402
Epoch 78/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7405
Epoch 79/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7404
Epoch 80/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7410
Epoch 81/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7408
Epoch 82/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7407
Epoch 83/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7397
Epoch 84/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7397
Epoch 85/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7400
Epoch 86/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7409
Epoch 87/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7388
Epoch 88/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5365 - accuracy: 0.7400
Epoch 89/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7407
Epoch 90/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7407
Epoch 91/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7390
Epoch 92/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7398
Epoch 93/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7401
Epoch 94/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5365 - accuracy: 0.7403
Epoch 95/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7397
Epoch 96/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7413
Epoch 97/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7404
Epoch 98/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7392
Epoch 99/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7398
Epoch 100/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7401
Epoch 101/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5377 - accuracy: 0.7393
Epoch 102/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7403
Epoch 103/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7397
Epoch 104/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7414
Epoch 105/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7400
Epoch 106/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7399
Epoch 107/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7394
Epoch 108/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7402
Epoch 109/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7390
Epoch 110/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7400
Epoch 111/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7401
Epoch 112/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7399
Epoch 113/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 114/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7401
Epoch 115/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7402
Epoch 116/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7406
Epoch 117/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7406
Epoch 118/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7396
Epoch 119/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7400
Epoch 120/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7403
Epoch 121/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7413
Epoch 122/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5375 - accuracy: 0.7387
Epoch 123/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7407
Epoch 124/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7386
Epoch 125/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7398
Epoch 126/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7402
Epoch 127/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7406
Epoch 128/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5370 - accuracy: 0.7411
Epoch 129/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7392
Epoch 130/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7385
Epoch 131/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7411
Epoch 132/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7402
Epoch 133/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7400
Epoch 134/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7402
Epoch 135/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5368 - accuracy: 0.7409
Epoch 136/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7393
Epoch 137/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7409
Epoch 138/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7400
Epoch 139/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7405
Epoch 140/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7395
Epoch 141/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5365 - accuracy: 0.7401
Epoch 142/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7408
Epoch 143/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7409
Epoch 144/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7400
Epoch 145/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7395
Epoch 146/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7396
Epoch 147/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7406
Epoch 148/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5377 - accuracy: 0.7394
Epoch 149/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7400
Epoch 150/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7404

In [58]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5704 - accuracy: 0.7229 - 517ms/epoch - 2ms/step
Loss: 0.5704401135444641, Accuracy: 0.7229154706001282

In [ ]:
# Export our model to HDF5 file
model_file_path = 'AlphabetSoupCharity.h5'
nn.save(model_file_path)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(